# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: admin.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'admin.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x61\x64min.proto\x12\x05\x61\x64min\"<\n\x0e\x41\x64\x64ShowRequest\x12\x15\n\rsession_token\x18\x01 \x01(\t\x12\x13\n\x0bmovie_title\x18\x02 \x01(\t\"D\n\x0f\x41\x64\x64ShowResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07show_id\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\"K\n\x0f\x41\x64\x64SeatsRequest\x12\x15\n\rsession_token\x18\x01 \x01(\t\x12\x0f\n\x07show_id\x18\x02 \x01(\t\x12\x10\n\x08seat_ids\x18\x03 \x03(\t\"4\n\x10\x41\x64\x64SeatsResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"H\n\x14ProcessRefundRequest\x12\x15\n\rsession_token\x18\x01 \x01(\t\x12\x19\n\x11payment_reference\x18\x02 \x01(\t\"9\n\x15ProcessRefundResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xd1\x01\n\x0c\x41\x64minService\x12\x38\n\x07\x41\x64\x64Show\x12\x15.admin.AddShowRequest\x1a\x16.admin.AddShowResponse\x12;\n\x08\x41\x64\x64Seats\x12\x16.admin.AddSeatsRequest\x1a\x17.admin.AddSeatsResponse\x12J\n\rProcessRefund\x12\x1b.admin.ProcessRefundRequest\x1a\x1c.admin.ProcessRefundResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'admin_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ADDSHOWREQUEST']._serialized_start=22
  _globals['_ADDSHOWREQUEST']._serialized_end=82
  _globals['_ADDSHOWRESPONSE']._serialized_start=84
  _globals['_ADDSHOWRESPONSE']._serialized_end=152
  _globals['_ADDSEATSREQUEST']._serialized_start=154
  _globals['_ADDSEATSREQUEST']._serialized_end=229
  _globals['_ADDSEATSRESPONSE']._serialized_start=231
  _globals['_ADDSEATSRESPONSE']._serialized_end=283
  _globals['_PROCESSREFUNDREQUEST']._serialized_start=285
  _globals['_PROCESSREFUNDREQUEST']._serialized_end=357
  _globals['_PROCESSREFUNDRESPONSE']._serialized_start=359
  _globals['_PROCESSREFUNDRESPONSE']._serialized_end=416
  _globals['_ADMINSERVICE']._serialized_start=419
  _globals['_ADMINSERVICE']._serialized_end=628
# @@protoc_insertion_point(module_scope)
