# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/auth.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'protos/auth.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11protos/auth.proto\x12\x04\x61uth\"2\n\x0cLoginRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"Y\n\rLoginResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x15\n\rsession_token\x18\x02 \x01(\t\x12\x0f\n\x07user_id\x18\x03 \x01(\t\x12\x0f\n\x07message\x18\x04 \x01(\t\"&\n\rLogoutRequest\x12\x15\n\rsession_token\x18\x01 \x01(\t\"2\n\x0eLogoutResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"/\n\x16ValidateSessionRequest\x12\x15\n\rsession_token\x18\x01 \x01(\t\"N\n\x17ValidateSessionResponse\x12\x10\n\x08is_valid\x18\x01 \x01(\x08\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x10\n\x08is_admin\x18\x03 \x01(\x08\x32\xc4\x01\n\x0b\x41uthService\x12\x30\n\x05Login\x12\x12.auth.LoginRequest\x1a\x13.auth.LoginResponse\x12\x33\n\x06Logout\x12\x13.auth.LogoutRequest\x1a\x14.auth.LogoutResponse\x12N\n\x0fValidateSession\x12\x1c.auth.ValidateSessionRequest\x1a\x1d.auth.ValidateSessionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOGINREQUEST']._serialized_start=27
  _globals['_LOGINREQUEST']._serialized_end=77
  _globals['_LOGINRESPONSE']._serialized_start=79
  _globals['_LOGINRESPONSE']._serialized_end=168
  _globals['_LOGOUTREQUEST']._serialized_start=170
  _globals['_LOGOUTREQUEST']._serialized_end=208
  _globals['_LOGOUTRESPONSE']._serialized_start=210
  _globals['_LOGOUTRESPONSE']._serialized_end=260
  _globals['_VALIDATESESSIONREQUEST']._serialized_start=262
  _globals['_VALIDATESESSIONREQUEST']._serialized_end=309
  _globals['_VALIDATESESSIONRESPONSE']._serialized_start=311
  _globals['_VALIDATESESSIONRESPONSE']._serialized_end=389
  _globals['_AUTHSERVICE']._serialized_start=392
  _globals['_AUTHSERVICE']._serialized_end=588
# @@protoc_insertion_point(module_scope)
