# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: booking.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'booking.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rbooking.proto\x12\x07\x62ooking\"U\n\x04Show\x12\n\n\x02id\x18\x01 \x01(\t\x12\x13\n\x0bmovie_title\x18\x02 \x01(\t\x12\x13\n\x0btotal_seats\x18\x03 \x01(\x05\x12\x17\n\x0f\x61vailable_seats\x18\x04 \x01(\x05\"(\n\x04Seat\x12\n\n\x02id\x18\x01 \x01(\t\x12\x14\n\x0cis_available\x18\x02 \x01(\x08\"$\n\x11GetSeatMapRequest\x12\x0f\n\x07show_id\x18\x01 \x01(\t\"\x8a\x01\n\x12GetSeatMapResponse\x12\x0f\n\x07show_id\x18\x01 \x01(\t\x12\x35\n\x05seats\x18\x02 \x03(\x0b\x32&.booking.GetSeatMapResponse.SeatsEntry\x1a,\n\nSeatsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x08:\x02\x38\x01\"\x8a\x01\n\x12ReserveSeatRequest\x12\x15\n\rsession_token\x18\x01 \x01(\t\x12\x0f\n\x07show_id\x18\x02 \x01(\t\x12\x0f\n\x07seat_id\x18\x03 \x01(\t\x12\x14\n\x0c\x61mount_cents\x18\x04 \x01(\x03\x12\x10\n\x08\x63urrency\x18\x05 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x06 \x01(\t\"f\n\x13ReserveSeatResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x12\n\nbooking_id\x18\x02 \x01(\t\x12\x19\n\x11payment_reference\x18\x03 \x01(\t\x12\x0f\n\x07message\x18\x04 \x01(\t\"A\n\x14\x43\x61ncelBookingRequest\x12\x15\n\rsession_token\x18\x01 \x01(\t\x12\x12\n\nbooking_id\x18\x02 \x01(\t\"9\n\x15\x43\x61ncelBookingResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x12\n\x10ListShowsRequest\"1\n\x11ListShowsResponse\x12\x1c\n\x05shows\x18\x01 \x03(\x0b\x32\r.booking.Show2\xb5\x02\n\x0e\x42ookingService\x12\x45\n\nGetSeatMap\x12\x1a.booking.GetSeatMapRequest\x1a\x1b.booking.GetSeatMapResponse\x12H\n\x0bReserveSeat\x12\x1b.booking.ReserveSeatRequest\x1a\x1c.booking.ReserveSeatResponse\x12N\n\rCancelBooking\x12\x1d.booking.CancelBookingRequest\x1a\x1e.booking.CancelBookingResponse\x12\x42\n\tListShows\x12\x19.booking.ListShowsRequest\x1a\x1a.booking.ListShowsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'booking_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETSEATMAPRESPONSE_SEATSENTRY']._loaded_options = None
  _globals['_GETSEATMAPRESPONSE_SEATSENTRY']._serialized_options = b'8\001'
  _globals['_SHOW']._serialized_start=26
  _globals['_SHOW']._serialized_end=111
  _globals['_SEAT']._serialized_start=113
  _globals['_SEAT']._serialized_end=153
  _globals['_GETSEATMAPREQUEST']._serialized_start=155
  _globals['_GETSEATMAPREQUEST']._serialized_end=191
  _globals['_GETSEATMAPRESPONSE']._serialized_start=194
  _globals['_GETSEATMAPRESPONSE']._serialized_end=332
  _globals['_GETSEATMAPRESPONSE_SEATSENTRY']._serialized_start=288
  _globals['_GETSEATMAPRESPONSE_SEATSENTRY']._serialized_end=332
  _globals['_RESERVESEATREQUEST']._serialized_start=335
  _globals['_RESERVESEATREQUEST']._serialized_end=473
  _globals['_RESERVESEATRESPONSE']._serialized_start=475
  _globals['_RESERVESEATRESPONSE']._serialized_end=577
  _globals['_CANCELBOOKINGREQUEST']._serialized_start=579
  _globals['_CANCELBOOKINGREQUEST']._serialized_end=644
  _globals['_CANCELBOOKINGRESPONSE']._serialized_start=646
  _globals['_CANCELBOOKINGRESPONSE']._serialized_end=703
  _globals['_LISTSHOWSREQUEST']._serialized_start=705
  _globals['_LISTSHOWSREQUEST']._serialized_end=723
  _globals['_LISTSHOWSRESPONSE']._serialized_start=725
  _globals['_LISTSHOWSRESPONSE']._serialized_end=774
  _globals['_BOOKINGSERVICE']._serialized_start=777
  _globals['_BOOKINGSERVICE']._serialized_end=1086
# @@protoc_insertion_point(module_scope)
