# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import booking_pb2 as booking__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in booking_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BookingServiceStub(object):
    """Service for movie ticket booking operations
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSeatMap = channel.unary_unary(
                '/booking.BookingService/GetSeatMap',
                request_serializer=booking__pb2.GetSeatMapRequest.SerializeToString,
                response_deserializer=booking__pb2.GetSeatMapResponse.FromString,
                _registered_method=True)
        self.ReserveSeat = channel.unary_unary(
                '/booking.BookingService/ReserveSeat',
                request_serializer=booking__pb2.ReserveSeatRequest.SerializeToString,
                response_deserializer=booking__pb2.ReserveSeatResponse.FromString,
                _registered_method=True)
        self.CancelBooking = channel.unary_unary(
                '/booking.BookingService/CancelBooking',
                request_serializer=booking__pb2.CancelBookingRequest.SerializeToString,
                response_deserializer=booking__pb2.CancelBookingResponse.FromString,
                _registered_method=True)
        self.ListShows = channel.unary_unary(
                '/booking.BookingService/ListShows',
                request_serializer=booking__pb2.ListShowsRequest.SerializeToString,
                response_deserializer=booking__pb2.ListShowsResponse.FromString,
                _registered_method=True)


class BookingServiceServicer(object):
    """Service for movie ticket booking operations
    """

    def GetSeatMap(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReserveSeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelBooking(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListShows(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BookingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetSeatMap': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSeatMap,
                    request_deserializer=booking__pb2.GetSeatMapRequest.FromString,
                    response_serializer=booking__pb2.GetSeatMapResponse.SerializeToString,
            ),
            'ReserveSeat': grpc.unary_unary_rpc_method_handler(
                    servicer.ReserveSeat,
                    request_deserializer=booking__pb2.ReserveSeatRequest.FromString,
                    response_serializer=booking__pb2.ReserveSeatResponse.SerializeToString,
            ),
            'CancelBooking': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelBooking,
                    request_deserializer=booking__pb2.CancelBookingRequest.FromString,
                    response_serializer=booking__pb2.CancelBookingResponse.SerializeToString,
            ),
            'ListShows': grpc.unary_unary_rpc_method_handler(
                    servicer.ListShows,
                    request_deserializer=booking__pb2.ListShowsRequest.FromString,
                    response_serializer=booking__pb2.ListShowsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'booking.BookingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('booking.BookingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BookingService(object):
    """Service for movie ticket booking operations
    """

    @staticmethod
    def GetSeatMap(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/booking.BookingService/GetSeatMap',
            booking__pb2.GetSeatMapRequest.SerializeToString,
            booking__pb2.GetSeatMapResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReserveSeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/booking.BookingService/ReserveSeat',
            booking__pb2.ReserveSeatRequest.SerializeToString,
            booking__pb2.ReserveSeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelBooking(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/booking.BookingService/CancelBooking',
            booking__pb2.CancelBookingRequest.SerializeToString,
            booking__pb2.CancelBookingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListShows(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/booking.BookingService/ListShows',
            booking__pb2.ListShowsRequest.SerializeToString,
            booking__pb2.ListShowsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
