# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/chatbot.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'protos/chatbot.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14protos/chatbot.proto\x12\x07\x63hatbot\":\n\x12\x41skQuestionRequest\x12\x15\n\rsession_token\x18\x01 \x01(\t\x12\r\n\x05query\x18\x02 \x01(\t\"7\n\x13\x41skQuestionResponse\x12\x0e\n\x06\x61nswer\x18\x01 \x01(\t\x12\x10\n\x08\x66rom_llm\x18\x02 \x01(\x08\x32Z\n\x0e\x43hatbotService\x12H\n\x0b\x41skQuestion\x12\x1b.chatbot.AskQuestionRequest\x1a\x1c.chatbot.AskQuestionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.chatbot_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ASKQUESTIONREQUEST']._serialized_start=33
  _globals['_ASKQUESTIONREQUEST']._serialized_end=91
  _globals['_ASKQUESTIONRESPONSE']._serialized_start=93
  _globals['_ASKQUESTIONRESPONSE']._serialized_end=148
  _globals['_CHATBOTSERVICE']._serialized_start=150
  _globals['_CHATBOTSERVICE']._serialized_end=240
# @@protoc_insertion_point(module_scope)
